version: '3.8'

services:
  # MariaDB 데이터베이스
  db:
    image: mariadb:10.11
    container_name: object_monitor_db_prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./back_end/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - object_monitor_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  # 백엔드 API 서버
  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    container_name: object_monitor_backend_prod
    restart: unless-stopped
    ports:
      - "5010:5010"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./back_end/uploads:/app/uploads
      - ./back_end/image:/app/image
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    networks:
      - object_monitor_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5010/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx 리버스 프록시 (선택사항)
  nginx:
    image: nginx:alpine
    container_name: object_monitor_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - object_monitor_network

volumes:
  db_data:
    driver: local

networks:
  object_monitor_network:
    driver: bridge
